{% set name = "gtdb_validation_tk" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8ea51e8f08f5fe9ce9686fb55c1c321b16000d749b3518f73aad3e4d9eff058

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gtdb_validation_tk = gtdb_validation_tk.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.8.0
    - biolib >=0.1.6
    - dendropy >=4.0.0
    - fuzzywuzzy
    - phylorank >=0.1.0

test:
  imports:
    - gtdb_validation_tk
  commands:
    - gtdb_validation_tk -h

about:
  home: https://github.com/Ecogenomics/gtdb_validation_tk
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: |
    This toolkit provides functionality for validation the GTDB Taxonomy.
    It is primarily intended to be used by the GTDB curation team, but has been
    made available in case others find it useful.

extra:
  recipe-maintainers:
    - aaronmussig
    - dparks1134
